<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<meta';
echo 'name="viewport"';
echo 'content="width=device-width, initial-scale=1, shrink-to-fit=no"';
echo '/>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"';
echo 'integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"';
echo 'crossorigin="anonymous"';
echo '/>';
echo '<title>Library Management System</title>';
echo '</head>';
echo '';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<a class="navbar-brand" href="#">Online Library</a>';
echo '<button';
echo 'class="navbar-toggler"';
echo 'type="button"';
echo 'data-toggle="collapse"';
echo 'data-target="#navbarSupportedContent"';
echo 'aria-controls="navbarSupportedContent"';
echo 'aria-expanded="false"';
echo 'aria-label="Toggle navigation"';
echo '>';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbarSupportedContent">';
echo '<ul class="navbar-nav mr-auto">';
echo '<li class="nav-item active">';
echo '<a class="nav-link" href="#"';
echo '>Home <span class="sr-only">(current)</span></a';
echo '>';
echo '</li>';
echo '</ul>';
echo '<form class="form-inline my-2 my-lg-0">';
echo '<input';
echo 'class="form-control mr-sm-2"';
echo 'type="search"';
echo 'placeholder="Search"';
echo 'aria-label="Search"';
echo '/>';
echo '<button class="btn btn-outline-success my-2 my-sm-0" type="submit">';
echo 'Search';
echo '</button>';
echo '</form>';
echo '</div>';
echo '</nav>';
echo '<div id="alertuser"></div>';
echo '';
echo '<div class="container my-3">';
echo '<h1>Welcome to My Library</h1>';
echo '<hr />';
echo '<form id="mylibraryform">';
echo '<div class="form-group">';
echo '<label for="exampleInputEmail1">User Name</label>';
echo '<input';
echo 'type="text"';
echo 'class="form-control"';
echo 'id="User-Name"';
echo 'aria-describedby="emailHelp"';
echo '/>';
echo '<small id="emailHelp" class="form-text text-muted"';
echo '>We'll never share your user name with anyone else.</small';
echo '>';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="exampleInputPassword1">Book Name</label>';
echo '<input type="text" class="form-control" id="Book-Name" />';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="bookType">Book Type</label>';
echo '<div class="check-boxes my-3 mx-5">';
echo '<div class="form-check p-2">';
echo '<input';
echo 'class="form-check-input"';
echo 'type="radio"';
echo 'name="check-box"';
echo 'id="Fiction"';
echo 'value="Fiction"';
echo '/>';
echo '<label class="form-check-label" for="Fiction"> Fiction </label>';
echo '</div>';
echo '<div class="form-check p-2">';
echo '<input';
echo 'class="form-check-input"';
echo 'type="radio"';
echo 'name="check-box"';
echo 'id="Programing"';
echo 'value="Programing"';
echo '/>';
echo '<label class="form-check-label" for="Programing">';
echo 'Programing';
echo '</label>';
echo '</div>';
echo '<div class="form-check p-2">';
echo '<input';
echo 'class="form-check-input"';
echo 'type="radio"';
echo 'name="check-box"';
echo 'id="Cooking"';
echo 'value="Cooking"';
echo '/>';
echo '<label class="form-check-label" for="Cooking"> Cooking </label>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<button type="submit" class="btn btn-outline-dark">Add Book</button>';
echo '</form>';
echo '<table class="table table-dark my-3">';
echo '<thead>';
echo '<tr>';
echo '<th scope="col">Sl No.</th>';
echo '<th scope="col">Date of issue</th>';
echo '<th scope="col">Reader</th>';
echo '<th scope="col">Book Name</th>';
echo '<th scope="col">Genre</th>';
echo '<th scope="col"></th>';
echo '</tr>';
echo '</thead>';
echo '<tbody id="table-body"></tbody>';
echo '</table>';
echo '</div>';
echo '';
echo '<script src="script.js"></script>';
echo '<script';
echo 'src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"';
echo 'integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"';
echo 'crossorigin="anonymous"';
echo '></script>';
echo '<script';
echo 'src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"';
echo 'integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"';
echo 'crossorigin="anonymous"';
echo '></script>';
echo '</body>';
echo '</html>';
echo '';
?>